"""
Module for initializing and exposing Tekla Structures OpenAPI namespaces.

This module ensures that Tekla's .NET assemblies are properly loaded before any
Tekla-related imports are accessed. It provides a centralized entry point for
DLL loading and exposes commonly used classes for use throughout the application.
"""

from tekla_mcp_server.init import load_dlls

load_dlls()
from System import Type as SystemType, Array as SystemArray
from System.Reflection import BindingFlags
from System.Collections import ArrayList, Hashtable
from System.Collections.Generic import Dictionary, List
from Tekla.Structures import Identifier, TeklaStructuresDatabaseTypeEnum, PositionTypeEnum, DetailTypeEnum, AutoDirectionTypeEnum, TeklaStructuresInfo, TeklaStructuresSettings
from Tekla.Structures.Geometry3d import AABB, Point, Vector, LineSegment
from Tekla.Structures.Model import (
    Model,
    ModelObject,
    ModelObjectEnumerator,
    ModelObjectSelector,
    Phase,
    PhaseCollection,
    Assembly,
    BaseWeld,
    Beam,
    Boolean,
    BooleanPart,
    BoltArray,
    BoltGroup,
    BoltXYList,
    ContourPlate,
    ContourPoint,
    Offset,
    Part,
    Position,
    Reinforcement,
    Solid,
    TransformationPlane,
    ComponentInput,
    Component,
    CustomPart,
    Detail,
    Seam,
    Connection,
    BaseRebarGroup,
    RebarMesh,
    RebarStrand,
    SingleRebar,
    Grid,
    ReferenceModelObject,
    ClashCheckHandler,
    ClashCheckData,
    Events,
)
from Tekla.Structures.Model.Operations import Operation
from Tekla.Structures.Model.UI import Color, GraphicsDrawer, ModelObjectSelector as ModelObjectSelectorUI, ViewHandler, ModelObjectVisualization, TemporaryTransparency, View
from Tekla.Structures.Filtering import (
    BinaryFilterOperatorType,
    BinaryFilterExpressionCollection,
    BinaryFilterExpressionItem,
    NumericOperatorType,
    NumericConstantFilterExpression,
    StringConstantFilterExpression,
    BinaryFilterExpression,
    StringOperatorType,
    FilterExpression,
)
from Tekla.Structures.Filtering.Categories import PartFilterExpressions, ObjectFilterExpressions, TemplateFilterExpressions
from Tekla.Structures.Catalogs import CatalogHandler, MaterialItem, MaterialItemEnumerator, ProfileItem, ProfileItemEnumerator, RebarItem
from Tekla.Structures.Drawing import (
    Drawing,
    DrawingEnumerator,
    Mark,
    MarkBase,
    MarkSet,
    WeldMark,
    DetailMark,
    LevelMark,
    SectionMark,
    SectionMarkBase,
    CurvedSectionMark,
    DimensionBase,
    DimensionSetBase,
    StraightDimension,
    StraightDimensionSet,
    AngleDimension,
    RadiusDimension,
    CurvedDimensionOrthogonal,
    CurvedDimensionRadial,
    CurvedDimensionSetOrthogonal,
    CurvedDimensionSetRadial,
    Text as DrawingText,
    GraphicObject,
    Cloud,
    Arc,
    Line,
    Circle,
    Polygon,
    Rectangle,
    Connection as DrawingConnection,
    DrawingObject,
    DrawingObjectEnumerator,
    ModelObject as DrawingModelObject,
    Frame,
    FrameTypes,
    DrawingColors,
    Polyline,
    PointList,
    DrawingHandler,
    LeaderLinePlacing,
    LeaderLine,
    DPMPrinterAttributes,
    DotPrintColor,
    DotPrintOrientationType,
    DotPrintOutputType,
    DotPrintPaperSize,
    DotPrintToMultipleSheet,
    DotPrintScalingType,
    View as DrawingView,
    ContainerView,
)


# Export everything
__all__ = [
    "SystemType",
    "SystemArray",
    "BindingFlags",
    "ArrayList",
    "Dictionary",
    "Hashtable",
    "List",
    "Identifier",
    "TeklaStructuresDatabaseTypeEnum",
    "PositionTypeEnum",
    "DetailTypeEnum",
    "AutoDirectionTypeEnum",
    "TeklaStructuresInfo",
    "TeklaStructuresSettings",
    "AABB",
    "Point",
    "Vector",
    "LineSegment",
    "Model",
    "ModelObject",
    "ModelObjectEnumerator",
    "ModelObjectSelector",
    "Assembly",
    "BaseWeld",
    "Beam",
    "Boolean",
    "BooleanPart",
    "BoltArray",
    "BoltGroup",
    "BoltXYList",
    "ContourPoint",
    "ContourPlate",
    "Part",
    "Phase",
    "PhaseCollection",
    "Position",
    "Solid",
    "TransformationPlane",
    "ComponentInput",
    "Component",
    "CustomPart",
    "Detail",
    "Seam",
    "Connection",
    "Reinforcement",
    "BaseRebarGroup",
    "RebarMesh",
    "RebarStrand",
    "SingleRebar",
    "Operation",
    "Color",
    "GraphicsDrawer",
    "ModelObjectSelectorUI",
    "ViewHandler",
    "ModelObjectVisualization",
    "TemporaryTransparency",
    "View",
    "BinaryFilterOperatorType",
    "BinaryFilterExpressionCollection",
    "BinaryFilterExpressionItem",
    "NumericOperatorType",
    "NumericConstantFilterExpression",
    "StringConstantFilterExpression",
    "BinaryFilterExpression",
    "StringOperatorType",
    "FilterExpression",
    "PartFilterExpressions",
    "ObjectFilterExpressions",
    "TemplateFilterExpressions",
    "CatalogHandler",
    "MaterialItem",
    "MaterialItemEnumerator",
    "ProfileItem",
    "ProfileItemEnumerator",
    "RebarItem",
    "DrawingHandler",
    "Drawing",
    "DrawingEnumerator",
    "Mark",
    "MarkBase",
    "MarkSet",
    "WeldMark",
    "DetailMark",
    "LevelMark",
    "SectionMark",
    "SectionMarkBase",
    "CurvedSectionMark",
    "DimensionBase",
    "DimensionSetBase",
    "StraightDimension",
    "StraightDimensionSet",
    "AngleDimension",
    "RadiusDimension",
    "CurvedDimensionOrthogonal",
    "CurvedDimensionRadial",
    "CurvedDimensionSetOrthogonal",
    "CurvedDimensionSetRadial",
    "DrawingText",
    "GraphicObject",
    "Cloud",
    "Arc",
    "Line",
    "Circle",
    "Polygon",
    "Rectangle",
    "DrawingConnection",
    "DrawingView",
    "ContainerView",
    "DrawingObject",
    "DrawingObjectEnumerator",
    "DrawingModelObject",
    "Frame",
    "FrameTypes",
    "DrawingColors",
    "Polyline",
    "PointList",
    "LeaderLine",
    "LeaderLinePlacing",
    "Grid",
    "Offset",
    "ReferenceModelObject",
    "DPMPrinterAttributes",
    "DotPrintColor",
    "DotPrintOrientationType",
    "DotPrintOutputType",
    "DotPrintPaperSize",
    "DotPrintToMultipleSheet",
    "DotPrintScalingType",
    "ClashCheckHandler",
    "ClashCheckData",
    "Events",
]
